import type { Metadata } from 'next'
import type { ReactNode } from 'react'

export const metadat: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  )
}

export default RootLayout